webkom/vote

Makefile
features/protractor-conf.js

>Protractor can test directly against Chrome and Firefox without using a Selenium Server. To use this, in your config file set directConnect: true.
>directConnect: true - Your test script communicates directly Chrome Driver or Firefox Driver, bypassing any Selenium Server. If this is true, settings for seleniumAddress and seleniumServerJar will be ignored. If you attempt to use a browser other than Chrome or Firefox an error will be thrown.
>The advantage of directly connecting to browser drivers is that your test scripts may start up and run faster.
https://angular.github.io/protractor/#/server-setup#connecting-directly-to-browser-drivers

Skip selenium and use the webdriver with chrome directly

---

app/views/partials/admin/editElection.pug
client/controllers/createElectionCtrl.js
client/controllers/editElectionCtrl.js

Adds a frontend button to the admin election page that copies the data of an existing election into the new election form, so that an election easily can be repeated with one alternative less or similar.
Fixes #115.

Add a copy election button

---

app/models/election.js
test/api/alternative.test.js

Looks like mongoose broke `.push()` in version 5, but this seems to work.

Fix a bug with creating additional alternatives

---

.drone.yml

`node:14-browsers` now has Chrome v86 so it will run for now
```sh
$ docker run -it circleci/node:14-browsers
$ google-chrome --version
Google Chrome 86.0.4240.198
```

Enable protractor tests for CI

---

client/services/cardKeyService.js

So they decided to change baudrate to baudRate in our experimental feature :shock:﻿
old
new

baudrate is now baudRate https://web.dev/serial/

---

.gitignore
README.md
app/views/partials/moderator/serial_error.pug
app/views/partials/moderator/showqr.pug
client/styles/admin.styl

Some iPhone users need the QR quite far away, while some android users need the QR code very close.
This fixes that:
> (it's actually 60fps, but the Gif looks like shit)

Make the QR use a pulse animation

---

app/views/layout.pug
client/styles/main.styl

This reverts commit af9c893bee0c8a6e1c7c64ed65d60d7d53046441.
Fun idea, but it doesn't make sense when people other than Abakus want to use the application.

Move logo out of header

---

.prettierignore
app/errors/index.js
app/stv/stv.js
app/stv/stv.ts
package.json
tsconfig.json
yarn.lock

Helps to solve #351, #361 and #378 
This is the main logic to elect candidates based only on the `(votes, alternatives, seats) => ()` of the election.
Credits go to @JonasBak for writing 95% of the logic. I've just adjusted it to fit into **Vote**.
As one might see, there are a lot of TypeScript comments in the file, as the original implementation was done in TypeScript while creating it. We still have many of the types here to give an overview of what the different `Object {}` are.

STV Core algorithm implementation

---

.drone.yml
Dockerfile
app/digital/mail.js
docker-compose.yml
env.js

I have been using `mongo:4.4` and `node:14` the whole time 🤷🏻 . Might as well put it up in `:develop` while we are testing things online. 
The image of VOTE running in prod right now is the one build on this Dockerfile (as I built it manually.)

Fix env in PROD, and bumb versions

---

app/views/partials/admin/editElection.pug
client/controllers/editElectionCtrl.js
client/styles/admin.styl

closes #383 
Fixes admin edit election page to look like it should with the style changes added.
- Also makes the access code a little more visible
- And adds a little gimmick to copy the access code with an icon/button :grin:.

Fix edit election page to match new alternatives styles

---

app/views/partials/retrieveVote.pug
client/styles/election.styl

The receipt now looks like this:
The text on the ballot is also uppercased on the ballot to match the look when prioritizing alternatives for an election.

Reuse ballot confirmation component on receipt page

---

README.md
app.js
app/controllers/election.js
app/controllers/user.js
app/digital/mail.js
app/digital/template.html
app/errors/index.js
app/models/user.js
app/views/layout.pug
app/views/partials/admin/editElection.pug
client/controllers/generateUserCtrl.js
client/login.js
deployment/docker-compose.yml
env.js
test/api/user.test.js
test/helpers.js

Resolved: #393 
Resolves: #399 
This change fixes a bunch of the mail and user generation problems we had.
- Include "username" and "password" in the mail template so people understand what is what
- Make the "Logg inn" link into a button
- Make the "Logg inn" href an `ENV` so it can be changed
- Add the `username` and `password` as a `?token=` query param. This is on the same schema as the QR version, so we can reuse that code for autofill
- Remove some links from the template to try to avoid `thrash` and `commercial` tags in inboxes.
- Make the mail-handler and user-gen toss some better errors, and add tests to make sure everything works as expected.
- Add support for -3- different `transporter` objects. 
- The default is just a promise, so the mail works without any other stuff. 
- The …

More user gen mail

---

app/views/partials/moderator/serial_error.pug
client/services/cardKeyService.js

This adds web nfc support on modern Android devices. Registers the same
keys as the web serial one, with a few exceptions. Most should be
possible to deal with tho.
Our white cards works similar on both, and the data format is the same.
Makes it way easier to host a vote, since you only need one android device with nfc. Android devices can also be connected to an external monitor as well, making them a cheap and easy solution :100: 
Example of web nfc: https://googlechrome.github.io/samples/web-nfc/

Add web nfc support

---

app/views/partials/election.pug
client/controllers/electionCtrl.js

Fixes #435 
This is pretty much how the old view was before, but with the "new" styling and the confirmation page.
There is no difference in how the data is posted. (There is a list with only one alternative)
Also adds a reset button to the bottom that resets the users current voting state. (clears all alternatives and refetches the election.

Add view for normal election voting in addition to stv

---

package.json

Years ago, when struggling with protractor and CI, we configured this webdriver-manager forced update when 
running the E2E tests. This has worked great, but the chrome version has to be manually hardcoded. 
Since drone is configured to run on circleci/node:16-browsers we never know when they (circle) decide to 
upgrade their chrome version. I see now (from recent CI runs), that they have bumped their version, so we must 
do the same.
This is sub-optimal. I will create an issue about looking into this :)

Bump chrome version to match circleci/node:16-browsers

---

.babelrc
app.ts
bin/users.ts
package.json
yarn.lock

Explicitly set mongoose strictQuery to true. This will be default false
in the next release.
Upgrade and specify the core-js version for babel as per their warning.

Fix some deprecations warnings

---

deployment/sync/README.md
deployment/sync/main.go

This adds the `-init` option to the sync script that will loop over all
registrations on the event and register the users in vote. E.x. run this
once, and then run without `-init` to only listen to incoming
websockets.

Add feature to sync script to register all users.

---

.drone.yml
app.ts
app/controllers/vote.ts
app/errors/index.ts
bin/users.ts
env.ts
test/api/vote.test.js
test/cleanup.js
test/cli/users.test.js
test/setup.js
vitest.config.ts

By using a separate DB in mongo for each thread, we can easily
parallelize all tests.
Resolves ABA-229

Enable parallel tests in vitest

---

app/routes/index.ts
package.json
server.ts
src/lib/components/Alerts.svelte
src/lib/components/Footer.svelte
src/lib/components/Navbar.svelte
src/lib/socketIOService.ts
src/lib/stores.ts
src/lib/utils/callApi.ts
src/routes/(election)/+page.svelte
src/routes/(election)/STVAlternativesList.svelte
src/routes/(election)/STVPriorityList.svelte
src/routes/(election)/STVPriorityListItem.svelte
src/routes/(election)/ToggleList.svelte
src/routes/(election)/retrieve/+page.svelte
src/routes/+layout.svelte
src/routes/auth/login/+page.svelte
src/variables.scss
tsconfig.json
vite.client.ts
vite.config.ts
yarn.lock

~~_Work in progress_~~ Finished :tm:
- The page to vote :ballot_box_with_check: 
- The page to verify your vote `/retrieve`
- An alert-service called `alerts` (should behave in the same way as the previous, with some changes to the api)
- `socketIOService` and the use of socket-io in development mode
- A logout button :o
- Rewrite css to scss, allowing more expressive styling
- Simplified routing logic some more
- Retrieved backend types with the `$backend` alias

Move pages used by a normal user to svelte

---

.drone.yml
app/digital/template.html
app/routes/api/auth.ts
app/routes/index.ts
cypress.d.ts
cypress/config/tasks.ts
cypress/e2e/election.cy.ts
cypress/e2e/moderator.cy.ts
cypress/plugins/smtp-test-server.ts
cypress/support/commands.ts
package.json
src/lib/components/Footer.svelte
src/lib/components/Navbar.svelte
src/lib/utils/callApi.ts
src/routes/(election)/+page.svelte
src/routes/(election)/retrieve/+page.svelte
src/routes/+layout.svelte
src/routes/auth/login/+page.svelte
src/routes/moderator/(useCardKey)/activate_user/+page.svelte
src/routes/moderator/(useCardKey)/change_card/+page.svelte
src/routes/moderator/(useCardKey)/create_user/+page.svelte
src/routes/moderator/(useCardKey)/deactivate_users/+page.svelte
src/routes/moderator/(useCardKey)/generate_user/+page.svelte
src/routes/moderator/(useCardKey)/manage_register/+page.svelte
src/routes/moderator/(useCardKey)/qr/+page.svelte
src/routes/moderator/serial_error/+page.svelte
types.d.ts
vite.config.ts
yarn.lock

Tested that behavior inside all /moderator-pages is as expected
- Updated `yarn test` to run the tests with correct environment variables
- Runs tests with the chrome browser, since that is what we support
- All card-scanner actions use the dummy-reader
- Added script for reading and verifying mails sent to users
Also commented out the coverage step, since it has not been used with cypress, though it should definitely be reimplemented:)

Add tests to moderator pages

---

.drone.yml

We only perform tests when they are merged into master, pushing to prod should only perform deployment :eyes:

Remove unnecessary steps from deployment

---

src/routes/moderator/serial_error/+page.svelte

Make it even more clear where to go to to enable Experimental Web Platform Features. Also makes it more convenient, having to read less :)

Update Moderator Tips on Serial Error Page to link to chrome flag page

---

usage.yml

Went through our calendar, emails, and notable events since Feb 2023 (and a little before to correct a missing event) until now, please let me know if anything is missing or if there is a typo but I'm pretty sure I got all the dates correct at least :D

Add usage for feb 2023 to apr 2024
