app/controllers/alternative.js
app/controllers/election.js
app/controllers/user.js
app/controllers/vote.js
app/routes/api/election.js
app/routes/api/index.js
app/routes/api/user.js
app/routes/helpers.js
app/views/adminIndex.jade
app/views/index.jade
app/views/partials/admin/editElection.jade
features/admin.feature
features/step_definitions/adminSteps.js
public/js/controllers/editElectionCtrl.js
public/js/services/adminElectionService.js
public/js/services/adminUserService.js
public/styles/admin.styl
test/api/api.test.js
test/api/election.test.js
test/api/user.test.js

* Shows total number of votes and total number of active users in the edit election frontend (fixes #76).
* Fixes preloading of elections in the election API (`app.param`).
* Makes use of express middleware to handle errors
* Adds 404 middleware for the API

Show counts in admin panel and fix error handling

---

app/models/election.js
app/views/partials/admin/editElection.jade
features/admin.feature
features/step_definitions/electionSteps.js
public/js/controllers/editElectionCtrl.js
test/api/vote.test.js

Restrict results on active election

---

app/controllers/user.js
test/api/user.test.js

Only count non-admin users

---

app/controllers/vote.js
app/views/index.jade
app/views/partials/admin/changeCard.jade
app/views/partials/admin/createElection.jade
app/views/partials/admin/createUser.jade
app/views/partials/retrieveVote.jade
features/admin.feature
features/election.feature
features/step_definitions/electionSteps.js
features/step_definitions/webSteps.js
features/support/hooks.js
public/js/appRoutes.js
public/js/controllers/electionCtrl.js
public/js/controllers/logoutCtrl.js
public/js/controllers/retrieveVoteCtrl.js
public/js/services/voteService.js
public/styles/main.styl
test/api/vote.test.js

Add retreive vote functionality

---

app/views/partials/elections.jade
app/views/partials/home.jade
features/admin.feature
features/step_definitions/webSteps.js
public/js/controllers/toggleUserController.js
public/js/services/alertService.js

Fixes #105 and adds a frontend test that verifies the behavior.

Only show one alert at a time when toggling user status

---

app/controllers/user.js
app/errors/error-checks.js
app/models/user.js
app/views/adminIndex.jade
app/views/index.jade
app/views/partials/admin/changeCard.jade
app/views/partials/admin/createUser.jade
app/views/partials/retrieveVote.jade
features/admin.feature
features/election.feature
features/step_definitions/adminSteps.js
features/step_definitions/electionSteps.js
features/step_definitions/webSteps.js
features/support/hooks.js
public/js/controllers/createUserCtrl.js
public/js/controllers/editElectionCtrl.js
public/styles/main.styl
test/api/auth.test.js
test/api/helpers.js
test/api/user.test.js

Adds error handling to createUsers, and provides feedback in the frontend if someone tries to register a user with an existing card. Also adds username validations to the backend, and refactors some of the cucumber code. All the frontend tests pass.
Fixes #107, #108, #109 and #110.

Fix user validations etc.

---

app/views/layout.jade
app/views/partials/admin/editElection.jade
features/step_definitions/adminSteps.js
public/js/controllers/editElectionCtrl.js
public/styles/admin.styl

Always nice with some last minute changes, completely forgot about this.

Show percentage for vote results

---

app/controllers/user.js
test/api/user.test.js

At the moment it just deactivates the first user it finds.

Make sure all users are deactivated

---

app/controllers/user.js
app/errors/index.js
client/controllers/createUserCtrl.js
features/admin.feature
test/api/user.test.js

Show a different error for existing usernames

---

electron-app/package.json
electron-app/yarn.lock

Tested and works fine with the readers and cards 👍

Change to 1.8.2 beta that fixes security issue

---

app/views/adminIndex.pug
app/views/index.pug
app/views/layout.pug

Remove tab to footer

---

app/views/adminIndex.pug
app/views/index.pug
app/views/layout.pug
app/views/partials/admin/createElection.pug
client/styles/admin.styl
client/styles/main.styl

Improve week styling by upping font size/weight

---

README.md
app/routes/index.js
app/views/layout.pug
app/views/usage.pug
client/styles/main.styl
package.json
usage.yml
yarn.lock

Add usage page

---

usage.yml

Missing the usages by Nablarevyen, but I'll get that fixed soon

Added usage by Nabla

---

README.md
app.js
app/views/layout.pug
electron-app/README.md
env.js

Add ENV variable for LOGO

---

Dockerfile
README.md
app.js
deployment/docker-compose.yml
env.js
server.js

This will need some quality assuranse. I am going to bed :sleeping:

Even more docs :tm:

---

.drone.yml
README.md
app/models/alternative.js
deployment/docker-compose.yml
docker-compose.yml
env.js
package.json
test/api/vote.test.js
yarn.lock

Race condition can appear because checking the users vote happens before saving that they have voted. If this happens in parallell a user is able to vote multiple times. This PR fixes this, but requires using redis to lock the vote.

Fix race condition and add test

---

usage.yml

Workz great atm! 💯 
Needs some tuning to make _vote_ perfect for NTNUI, will look into that later 🐌

Add usage for NTNUI-genfors 2019

---

app/views/partials/admin/elections.pug
client/styles/admin.styl

Just fooling around in `pug` and `styl` to get a hang of it again :)

Style and info to elections page

---

.drone.yml
package.json
yarn.lock

Add coverage to CI with upload to coveralls.
We have the command already, so why not?

Add coverage to CI

---

app/views/partials/admin/createElection.pug
client/styles/admin.styl

Resolves #352 
Resolved #378 
Should wait with this until we have set up the backend to support STV elections.

Edit admin view to include seat count

---

.eslintrc
app/views/partials/admin/editElection.pug
app/views/partials/retrieveVote.pug
client/controllers/editElectionCtrl.js
client/services/adminElectionService.js
client/styles/admin.styl
client/styles/main.styl
package.json
yarn.lock

Adds view for calculating the result **(admin feature)**. Closes #360
Adds view for showing your priorities via hash **(user feature)**. Closes #365

STV Result View

---

.gitignore
app.js
app/controllers/election.js
app/controllers/user.js
app/digital/mail.js
app/digital/template.html
app/errors/index.js
app/models/election.js
app/models/email.js
app/models/register.js
app/models/user.js
app/routes/api/user.js
app/routes/auth.js
app/views/moderatorIndex.pug
app/views/partials/admin/editElection.pug
app/views/partials/election.pug
app/views/partials/moderator/generateUser.pug
client/appRoutes.js
client/controllers/electionCtrl.js
client/controllers/generateUserCtrl.js
client/controllers/index.js
client/services/electionService.js
client/services/userService.js
client/styles/election.styl
docker-compose.yml
package.json
test/api/election.test.js
yarn.lock

Resolves #381
Resolves #382
The first feature is that we can generate users by their email using the moderator panel
> ![image](https://user-images.githubusercontent.com/23152018/104821382-b9e46580-583b-11eb-90c9-6c13c4a2d675.png)
<hr/>
They then get an email with the login details. The `username` is a parsed version of the email. The `password` is random crypto sting, and the `cardKey` becomes a UUID
> ![image](https://user-images.githubusercontent.com/23152018/104821402-e1d3c900-583b-11eb-90ca-3584eb549383.png)
The second feature is that, if your user is not active, you need a code to unlock your user and retrieve the election
> ![image](https://user-images.githubusercontent.com/23152018/104821478-69b9d300-583c-11eb-805c-28d3cea121f4.png)
Between each election (when the debate/pitch …

Digital VOTE with User generation and Accesscode

---

README.md
app/controllers/user.js
app/digital/mail.js
app/digital/template.html
app/errors/index.js
app/models/register.js
app/views/partials/moderator/generateUser.pug
client/controllers/generateUserCtrl.js
client/services/userService.js
env.js
package.json
yarn.lock

Made some changes to implement the flow discussed in Slack™️ .
The flow is as @odinuge suggested
1. Generate user => You don't have a `legoUser` entry in the register, so you get a new user.
2. Generate user => You do have a `legoUser` entry in the register (and a `user` entry meaning your user is not active yet), so we re-register your user with the new email, and change the password.
3. Generate user => You do have a `legoUser` entry in the register, with no `user` entry, meaning you have already activated the user, therefore we send a mail and tell "Sucks to be you"
It's not very "tested" yet, I just wanted to get the code up to see if people agree with the flow 👍🏻

Use LEGOUser to avoid duplicates, resend mail on duplicate

---

client/controllers/electionCtrl.js

Clear selected priorities on vote and fetchElection

---

app/controllers/user.js
app/stv/stv.js
app/stv/stv.ts
app/views/partials/admin/editElection.pug
client/styles/admin.styl
client/styles/main.styl
package.json
test/stv/blank.test.js
test/stv/datasets/dataset11.js
test/stv/datasets/dataset12.js
test/stv/datasets/dataset13.js
test/stv/datasets/index.js
yarn.lock

Fixes #395 
Fixes #400 
Also increases font size for the log and adds some tooltips.

Show blank votes & alternatives with 0 votes in election summary

---

app/controllers/election.js
app/controllers/user.js
app/errors/index.js
test/api/election.test.js

Only allow one active election

---

app/views/partials/admin/editElection.pug
features/election.feature
features/step_definitions/electionSteps.js
features/step_definitions/webSteps.js
features/support/hooks.js

Fixes E2E tests that no longer were relevant, as well as adds some more tests for then new UI and system.

Fix and add E2E tests for new STV voting

---

app/controllers/user.js
app/errors/index.js
app/models/register.js
app/views/partials/moderator/generateUser.pug
app/views/partials/moderator/manageRegister.pug
client/controllers/generateUserCtrl.js
deployment/sync/main.go
test/api/register.test.js
test/api/user.test.js

`Vote` and `LEGO` should be compatible but not dependent 👍🏻

Rename legoUser to identifier so it's not linked to LEGO

---

app/views/partials/admin/editElection.pug
features/admin.feature
features/step_definitions/adminSteps.js
features/step_definitions/webSteps.js

Fixes #355 
Not the best coverage, but it's a pain to write these tests :upside_down_face:

Some more E2E tests

---

usage.yml

Close: https://github.com/webkom/vote/issues/414

Update 2021 usage

---

.drone.yml
Dockerfile
app.js
app/views/layout.pug
docker-compose.yml
env.js
package.json

1) Switch over to use `the build` branch, like lego, and rename the image tag.
2) Embed the **RELEASE** in the image and display it in the footer. This is also a link that goes to that tag on dockerhub.

Docker build changes

---

app/views/partials/admin/createElection.pug
client/controllers/createElectionCtrl.js
client/styles/admin.styl
features/admin.feature
features/step_definitions/webSteps.js

Add toggle for stv/normal to create election page

---

app/controllers/user.ts
app/models/alternative.ts
app/models/election.ts
app/models/register.ts
app/models/user.ts
app/models/vote.ts
app/routes/api/user.ts
app/types/types.ts

Made types for all the models and placed these in a separate types.ts file. 
Rewrote all models to use these types, so now all the files in app/models are valid ts files.
Made ElectionTypes (says whether the election is normal or stv) into an enum, renamed it to ElectionSystems so the name isn't confused with all the new types, and moved it into the types.ts file.
This breaks some stuff in the rest off the app, but i'll fix this in a later pr.
What has to be done later is:
- Update refrences to ElectionTypes. It's not been renamed in any places it's used outside of app/models as the imports are outdated anyways; they use requires and point to the wrong location, so I figured this can be done in it's own pr
- Update types in the rest of the app. For example controllers now use some types …

Add model types

---

app/errors/index.ts
app/types/types.ts

Refactoring http-errors, as well as exporitng some more model types:)

Add types to HTTP-errors

---

.drone.yml
Dockerfile
app/digital/template.html
app/errors/index.ts
global.d.ts
webpack.config.js
webpack.server.js

- Rewrite Dockerfile to use multi-stage build
- The html template did not get included in the build.
- There was some incorrect configuration in the client webpack config
with the outputPath did not get put in the dist folder

Update to node 16 & fix some build errors

---

app/digital/mail.ts

This reverts commit 1c7a0f43ed21ad03ed2bcdafbb5e11dd8d7be076.

Revert "Temporary title change for GenVORS event"

---

HOWTO.md
README.md

As the usage of VOTE by other parties increases, we always have to send out a description of how they can use it, and in my experience it's being kinda made up on the fly by whomever.
This is an attempt to start to standardize those messages - so that we can just refer anyone to this file if they need an introduction to how it works.
This sums up what I've sent the most recent times, so it should be enough as a minimum that we can expand on later.
Resolves ABA-255

Add howto vote and update README.md

---

usage.yml

I've probably missed a few, but these were the ones we have emails about
closes ABA-130

Add usages since october 2021

---

Dockerfile

Build cli in dockerfile

---

Dockerfile

Add view to dockerfile

---

.drone.yml
Dockerfile
README.md
bin/users.ts
env.ts
package.json

For some reason it doesn't connect to mongodb at "localhost" in v18, we need to use "0.0.0.0" instead

Update node to v18

---

app/routes/index.ts
src/lib/components/Navbar.svelte
src/routes/usage/+page.svelte
tsconfig.json
usage.d.yml.ts
vite.client.ts

New Page:
times manymany
This is the final page!

Move usage page to svelte
